### ISSUE TITLE
Offline wokwi simulator

### ISSUE THREAD

**Issue by ricardojlrufino** [wokwi/wokwi-gdbserver#1]
Hi , how are you ?
I would like to know if there is a way to run the simulator offline.

My idea is to create a plugin for the arduino ide for it to compile and just do the simulation...

I already know how to do this with AVR8js, but I would like to know if it is possible to do it with ESP32 and others boards

**Comment by urish** [comment]
Hi Ricardo, great hearing from you again :-)

Not at the moment - there's an open request for this though: https://wokwi.com/features#feature-1021785941

How is it going with the AVR8js version?

**Comment by ricardojlrufino** [comment]
Hey friend !
First of all congratulations the project is amazing!!

I ended up choosing to use the implementation in "C", for being more performatic. But I didn't do anything practical just a few tests...

The Arduino IDE is still widely used in schools and courses. And I am uncomfortable with the fact that I don't have a simulator.
